### ISSUE TITLE
OCaml 5.3 support

### ISSUE THREAD

**Issue by kit-ty-kate** [stedolan/malfunction#44]
malfunction currently fails to build with the upcoming OCaml 5.3:
```
#=== ERROR while compiling malfunction.0.6 ====================================#
# context              2.3.0~alpha~dev | linux/x86_64 | ocaml-variants.5.3.0+trunk | file:///home/opam/opam-repository
# path                 ~/.opam/5.3/.opam-switch/build/malfunction.0.6
# command              ~/.opam/5.3/bin/dune build -p malfunction -j 1
# exit-code            1
# env-file             ~/.opam/log/malfunction-20-c96ea6.env
# output-file          ~/.opam/log/malfunction-20-c96ea6.out
### output ###
# (cd _build/default && /home/opam/.opam/5.3/bin/ocamlc.opt -w -40 -g -bin-annot -bin-annot-occurrences -I src/.malfunction.objs/byte -I /home/opam/.opam/5.3/lib/findlib -I /home/opam/.opam/5.3/lib/ocaml/compiler-libs -I /home/opam/.opam/5.3/lib/ocaml/dynlink -I /home/opam/.opam/5.3/lib/ocaml/str -I /home/opam/.opam/5.3/lib/ocaml/unix -I /home/opam/.opam/5.3/lib/zarith -intf-suffix .ml -no-alias-deps -o src/.malfunction.objs/byte/malfunction_compiler.cmo -c -impl src/malfunction_compiler.ml)
# File "src/malfunction_compiler.ml", line 774, characters 4-21:
# 774 |     Env.set_unit_name module_name;
#           ^^^^^^^^^^^^^^^^^
# Error: Unbound value "Env.set_unit_name"
```

**Comment by stedolan** [comment]
Thanks, will have a look.

**Comment by stedolan** [comment]
I should probably start putting explicit OCaml version upper bounds in the malfunction opam files?

Malfunction is very unlikely to work with an untested new release of the compiler since something always changes in compiler-libs.

**Comment by kit-ty-kate** [comment]
> I should probably start putting explicit OCaml version upper bounds in the malfunction opam files?

yeah probably

**Comment by stedolan** [comment]
Fixed in v0.7 (ocaml/opam-repository#26860), which now has a `< 5.4` version bound on `ocaml`
